#Définir un nom
name: Laravel CI

#Définir les triggers
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #1- Récupérer le code source
      - name: Récupérer le code source
        uses: actions/checkout@v5

      #2 Executer les test

      - name: Run test
        run: cd app && composer install && php artisan key:gen &&  php artisan test