#Définir un nom
name: Laravel CI

#Définir les triggers
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #1- Récupérer le code source
      - name: RCHeckout code
        uses: actions/checkout@v5

      #2 Executer les test

      - name: Run test
        run: cd app && composer install && cp .env.example .env && php artisan key:gen &&  php artisan test

      #3 Construire l'image
      - name: build app image
        run: docker build -t youssifnazega/laravel_cicd:latest .
      
      #4 Se connecter a docker hub
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOCKEN }}

      # 5 Poussé l'image sur la registry
      - name: Push image with new tag
        run: docker push youssifnazega/laravel_cicd:latest
